apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: laba1-api
          image: yauheniiyy/laba1-api:2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort
